# Generated by Django 3.1.2 on 2020-10-24 02:33

from django.db import migrations, models
import django_upload_path.upload_path


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=django_upload_path.upload_path.auto_cleaned_path_stripped_uuid4, verbose_name='imágen'),
        ),
    ]
