# Generated by Django 3.1.2 on 2020-10-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_thematic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='título'),
        ),
    ]
