# Generated by Django 3.1.2 on 2021-04-16 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210411_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectauthor',
            options={'verbose_name': 'autor', 'verbose_name_plural': 'autores'},
        ),
    ]
