# Generated by Django 3.1.2 on 2021-05-11 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_upload_path.upload_path
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universities', '0004_auto_20210415_2152'),
        ('projects', '0005_auto_20210415_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'ponencia', 'verbose_name_plural': 'ponencias'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='speaker',
        ),
        migrations.AddField(
            model_name='project',
            name='abstract',
            field=models.TextField(null=True, verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_project', to=settings.AUTH_USER_MODEL, verbose_name='autor principal'),
        ),
        migrations.AddField(
            model_name='projectauthor',
            name='document_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='projectauthor',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='projectauthor',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='projectauthor',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='projectauthor',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='university_project_Author', to='universities.university', verbose_name='Universidad / Organización'),
        ),
        migrations.AlterField(
            model_name='project',
            name='document',
            field=models.FileField(help_text='Solamente se permiten documentos en pdf', null=True, upload_to=django_upload_path.upload_path.auto_cleaned_path_stripped_uuid4, validators=[projects.models.ExtensionValidator(['pdf'])], verbose_name='documento (PDF)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='thematic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_talk', to='projects.thematic', verbose_name='eje temático'),
        ),
        migrations.AlterField(
            model_name='projectauthor',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='observación'),
        ),
        migrations.AlterUniqueTogether(
            name='projectauthor',
            unique_together={('document_number', 'project')},
        ),
        migrations.RemoveField(
            model_name='projectauthor',
            name='author',
        ),
    ]
