# Generated by Django 3.1.2 on 2021-05-17 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_upload_path.upload_path
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universities', '0004_auto_20210415_2152'),
        ('projects', '0006_auto_20210511_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='título')),
                ('image', models.ImageField(blank=True, null=True, upload_to=django_upload_path.upload_path.auto_cleaned_path_stripped_uuid4, verbose_name='imágen')),
                ('abstract', models.TextField(null=True, verbose_name='resumen')),
                ('video', models.FileField(help_text='Solamente se permiten archivos de vídeo', null=True, upload_to=django_upload_path.upload_path.auto_cleaned_path_stripped_uuid4, validators=[projects.models.ExtensionValidator(['MP4', 'AVI', 'MKV', 'FLV', 'MOV', 'WMV'])], verbose_name='vídeo (mp4, avi, flv, mov, wmv)')),
                ('link_url', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_VideoPoster', to=settings.AUTH_USER_MODEL, verbose_name='autor principal')),
                ('thematic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VideoPosterThematic', to='projects.thematic', verbose_name='eje temático')),
            ],
            options={
                'verbose_name': 'video poster',
                'verbose_name_plural': 'videos posters',
            },
        ),
        migrations.AlterModelOptions(
            name='projectauthor',
            options={'verbose_name': 'autor', 'verbose_name_plural': 'datos personales de los autores'},
        ),
        migrations.AlterField(
            model_name='project',
            name='abstract',
            field=models.TextField(null=True, verbose_name='resumen'),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_project', to=settings.AUTH_USER_MODEL, verbose_name='autor principal'),
        ),
        migrations.AlterField(
            model_name='projectauthor',
            name='document_number',
            field=models.CharField(max_length=30, null=True, verbose_name='documento'),
        ),
        migrations.AlterField(
            model_name='projectauthor',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='university_project_Author', to='universities.university', verbose_name='Universidad / Organización'),
        ),
        migrations.CreateModel(
            name='VideoPosterAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, null=True, verbose_name='last name')),
                ('document_number', models.CharField(max_length=30, null=True, verbose_name='documento')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='observación')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='university_video_poster_author', to='universities.university', verbose_name='Universidad / Organización')),
                ('videoPoster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videoPosterAuthor_VideoPoster', to='projects.videoposter', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'datos personales de los autores',
                'unique_together': {('document_number', 'videoPoster')},
            },
        ),
    ]
