# Generated by Django 3.1.2 on 2021-05-17 00:49

from django.db import migrations, models
import django_upload_path.upload_path
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210516_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoposter',
            name='video',
            field=models.FileField(help_text='Solamente se permiten archivos de vídeo', null=True, upload_to=django_upload_path.upload_path.auto_cleaned_path_stripped_uuid4, validators=[projects.models.ExtensionValidator(['mp4', 'avi', 'mkv', 'flv', 'mov', 'wmv'])], verbose_name='vídeo (mp4, avi, flv, mov, wmv)'),
        ),
    ]
