# Generated by Django 3.1.2 on 2021-05-19 00:12

from django.db import migrations, models
import django.db.models.deletion
import django_upload_path.upload_path


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210516_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to=django_upload_path.upload_path.auto_cleaned_path_stripped_uuid4, verbose_name='imágen')),
            ],
            options={
                'verbose_name': 'Eje temático',
                'verbose_name_plural': 'Ejes temáticos',
            },
        ),
        migrations.AddField(
            model_name='thematic',
            name='main_theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thematic_main_theme', to='projects.maintheme', verbose_name='tema principal'),
        ),
    ]
