# Generated by Django 3.1.2 on 2021-05-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210518_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_theme',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='eje temático'),
        ),
    ]
