# Generated by Django 3.1.2 on 2021-05-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_main_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thematic',
            name='main_theme',
        ),
        migrations.AlterField(
            model_name='project',
            name='main_theme',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='eje temático'),
        ),
        migrations.DeleteModel(
            name='MainTheme',
        ),
    ]
