# Generated by Django 3.1.2 on 2021-05-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210519_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoposter',
            name='main_theme',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='eje temático'),
        ),
    ]
