# Generated by Django 3.1.2 on 2021-05-27 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_upload_path.upload_path
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0012_videoposter_main_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='título')),
                ('image', models.ImageField(blank=True, null=True, upload_to=django_upload_path.upload_path.auto_cleaned_path_stripped_uuid4, verbose_name='imágen')),
                ('abstract', models.TextField(null=True, verbose_name='resumen')),
                ('main_theme', models.CharField(blank=True, max_length=100, null=True, verbose_name='eje temático')),
                ('document', models.FileField(help_text='Solamente se permiten documentos de word', null=True, upload_to=django_upload_path.upload_path.auto_cleaned_path_stripped_uuid4, validators=[projects.models.ExtensionValidator(['doc', 'docx', 'odt'])], verbose_name='documento (Word)')),
                ('link_url', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_project', to=settings.AUTH_USER_MODEL, verbose_name='autor principal')),
                ('thematic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_talk', to='projects.thematic', verbose_name='eje temático')),
            ],
            options={
                'verbose_name': 'ponencia',
                'verbose_name_plural': 'ponencias',
            },
        ),
        migrations.AlterField(
            model_name='projectauthor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projectAuthor_project', to='projects.presentation', verbose_name='proyecto'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
