# Generated by Django 3.1.2 on 2021-05-27 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_upload_path.upload_path


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_auto_20210526_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='main_theme',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='title',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='título')),
                ('image', models.ImageField(blank=True, null=True, upload_to=django_upload_path.upload_path.auto_cleaned_path_stripped_uuid4, verbose_name='imágen')),
                ('abstract', models.TextField(null=True, verbose_name='resumen')),
                ('main_theme', models.CharField(blank=True, max_length=100, null=True, verbose_name='eje temático')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_project', to=settings.AUTH_USER_MODEL, verbose_name='autor principal')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
            },
        ),
        migrations.AddField(
            model_name='presentation',
            name='project_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectauthor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projectAuthor_project', to='projects.project', verbose_name='proyecto'),
        ),
    ]
