# Generated by Django 3.1.2 on 2021-05-27 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20210526_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoposter',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='videoposter',
            name='author',
        ),
        migrations.RemoveField(
            model_name='videoposter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='videoposter',
            name='image',
        ),
        migrations.RemoveField(
            model_name='videoposter',
            name='main_theme',
        ),
        migrations.RemoveField(
            model_name='videoposter',
            name='thematic',
        ),
        migrations.RemoveField(
            model_name='videoposter',
            name='title',
        ),
        migrations.AddField(
            model_name='videoposter',
            name='project_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.project'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VideoPosterAuthor',
        ),
    ]
