# Generated by Django 3.1.2 on 2021-05-27 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20210526_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.project')),
            ],
            options={
                'verbose_name': 'poster',
                'verbose_name_plural': 'posters',
            },
            bases=('projects.project',),
        ),
    ]
