# Generated by Django 3.1.2 on 2021-05-27 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_upload_path.upload_path
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universities', '0004_auto_20210415_2152'),
        ('projects', '0016_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectauthor',
            name='document_type',
            field=models.CharField(choices=[('Passport', 'Pasaporte'), ('DNI', 'Documento Nacional de Identidad -D.N.I.'), ('LC', 'Libreta Cívica - L.C.'), ('LE', 'Libreta de Enrolamiento - L.E.')], default='Passport', max_length=15, null=True, verbose_name='TIPO DOCUMENTO'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='document',
            field=models.FileField(help_text='Solamente se permiten documentos de word', null=True, upload_to=django_upload_path.upload_path.auto_cleaned_path_stripped_uuid4, validators=[projects.models.ExtensionValidator(['doc', 'docx', 'odt'])], verbose_name='DOCUMENTO (Word)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='abstract',
            field=models.TextField(null=True, verbose_name='RESUMEN'),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_project', to=settings.AUTH_USER_MODEL, verbose_name='RESPONSABLE'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=django_upload_path.upload_path.auto_cleaned_path_stripped_uuid4, verbose_name='IMAGEN'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_theme',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='EJE TEMÁTICO'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='TÍTULO'),
        ),
        migrations.AlterField(
            model_name='projectauthor',
            name='document_number',
            field=models.CharField(max_length=30, null=True, verbose_name='NÚMERO DOCUMENTO'),
        ),
        migrations.AlterField(
            model_name='projectauthor',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='EMAIL ADDRESS'),
        ),
        migrations.AlterField(
            model_name='projectauthor',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='FIRST NAME'),
        ),
        migrations.AlterField(
            model_name='projectauthor',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='LAST NAME'),
        ),
        migrations.AlterField(
            model_name='projectauthor',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='university_project_Author', to='universities.university', verbose_name='UNIVERSIDAD'),
        ),
        migrations.AlterField(
            model_name='videoposter',
            name='video',
            field=models.FileField(help_text='Solamente se permiten archivos de vídeo', null=True, upload_to=django_upload_path.upload_path.auto_cleaned_path_stripped_uuid4, validators=[projects.models.ExtensionValidator(['mp4', 'avi', 'mkv', 'flv', 'mov', 'wmv'])], verbose_name='VÍDEO (mp4, avi, flv, mov, wmv)'),
        ),
    ]
