# Generated by Django 3.1.2 on 2021-05-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210527_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectauthor',
            options={'verbose_name': 'autor', 'verbose_name_plural': 'autores'},
        ),
        migrations.AlterField(
            model_name='projectauthor',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='CORREO ELECTRÓNICO'),
        ),
        migrations.AlterField(
            model_name='projectauthor',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='NOMBRE'),
        ),
        migrations.AlterField(
            model_name='projectauthor',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='APELLIDO'),
        ),
        migrations.AlterUniqueTogether(
            name='projectauthor',
            unique_together={('document_number', 'project', 'document_type')},
        ),
    ]
