# Generated by Django 3.1.2 on 2021-06-01 03:20

from django.db import migrations, models
import django_upload_path.upload_path
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoposter',
            name='video',
            field=models.FileField(help_text='Solamente se permiten archivos de vídeo o audio', null=True, upload_to=django_upload_path.upload_path.auto_cleaned_path_stripped_uuid4, validators=[projects.models.ExtensionValidator(['mp4', 'avi', 'mkv', 'flv', 'mov', 'wmv', 'mp3', 'm4a', 'flac', 'ogg', 'wma', 'aac'])], verbose_name='VÍDEO o AUDIO'),
        ),
    ]
