# Generated by Django 3.1.2 on 2021-06-01 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20210601_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectauthor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectAuthor_project', to='projects.project', verbose_name='proyecto'),
        ),
    ]
