# Generated by Django 3.1.2 on 2021-06-05 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0022_auto_20210601_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('RequestForChanges', 'Solicitud de cambios'), ('reviewed', 'Revisado'), ('Approved', 'Aprobado')], default='Pendiente', max_length=20, verbose_name='estado'),
        ),
        migrations.CreateModel(
            name='NoteProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='fecha')),
                ('note', models.TextField(verbose_name='nota')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
            },
        ),
    ]
