# Generated by Django 3.1.2 on 2021-06-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20210604_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_theme',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='EJE TEMÁTICO'),
        ),
        migrations.AlterField(
            model_name='projectauthor',
            name='document_number',
            field=models.CharField(max_length=60, null=True, verbose_name='NÚMERO DOCUMENTO'),
        ),
        migrations.AlterField(
            model_name='projectauthor',
            name='first_name',
            field=models.CharField(max_length=150, null=True, verbose_name='NOMBRE'),
        ),
    ]
