# Generated by Django 3.1.2 on 2021-06-09 23:29

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('projects', '0024_auto_20210607_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Proporcione una lista de palabras claves separadas por comas', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='palabras claves'),
        ),
    ]
