# Generated by Django 3.1.2 on 2021-07-19 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0025_auto_20210609_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='NOMBRE')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha y hora')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Link de YouTube')),
                ('zoom_url', models.URLField(blank=True, null=True, verbose_name='Link de Zoom')),
                ('observation', models.TextField(blank=True, verbose_name='observación')),
                ('moderator', models.ForeignKey(limit_choices_to={'user_type': 'Collaborator'}, on_delete=django.db.models.deletion.PROTECT, related_name='moderator_commission', to=settings.AUTH_USER_MODEL, verbose_name='MODERADOR')),
                ('technical_operator', models.ForeignKey(limit_choices_to={'user_type': 'Collaborator'}, on_delete=django.db.models.deletion.PROTECT, related_name='technical_operator_commission', to=settings.AUTH_USER_MODEL, verbose_name='MODERADOR')),
            ],
            options={
                'verbose_name': 'mesa',
                'verbose_name_plural': 'mesas',
                'unique_together': {('name', 'date_time')},
            },
        ),
    ]
