# Generated by Django 3.1.2 on 2021-07-19 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0026_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='FECHA Y HORA'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='technical_operator',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Collaborator'}, on_delete=django.db.models.deletion.PROTECT, related_name='technical_operator_commission', to=settings.AUTH_USER_MODEL, verbose_name='OPERADOR TÉCNICO'),
        ),
    ]
