# Generated by Django 3.1.2 on 2021-07-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20210718_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.CharField(blank=True, choices=[('1', 'Políticas públicas y Universidad: el rol de la extensión universitaria en el acompañamiento y asistencia en la pandemia por Covid-19'), ('2', 'Enfoques teóricos, metodológicos y prácticos para la curricularización de la extensión'), ('3', 'Praxis extensionistas y construcción colectiva del conocimiento'), ('4', 'Estrategias de gestión integral para el abordaje institucional de la extensión')], max_length=2, null=True, verbose_name='eje'),
        ),
    ]
