# Generated by Django 3.1.2 on 2021-07-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_project_theme'),
        ('projects', '0028_auto_20210722_2341'),
    ]

    operations = [
    ]
