# Generated by Django 3.1.2 on 2021-07-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_merge_20210724_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='amount_of_participants',
            field=models.IntegerField(blank=True, null=True, verbose_name='cant. de participantes'),
        ),
        migrations.AddField(
            model_name='commission',
            name='theme',
            field=models.CharField(blank=True, choices=[('1', 'Políticas públicas y Universidad: el rol de la extensión universitaria en el acompañamiento y asistencia en la pandemia por Covid-19'), ('2', 'Enfoques teóricos, metodológicos y prácticos para la curricularización de la extensión'), ('3', 'Praxis extensionistas y construcción colectiva del conocimiento'), ('4', 'Estrategias de gestión integral para el abordaje institucional de la extensión')], max_length=2, null=True, verbose_name='eje'),
        ),
    ]
