# Generated by Django 3.1.2 on 2021-07-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20210724_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='theme',
            field=models.CharField(choices=[('1', 'Políticas públicas y Universidad: el rol de la extensión universitaria en el acompañamiento y asistencia en la pandemia por Covid-19'), ('2', 'Enfoques teóricos, metodológicos y prácticos para la curricularización de la extensión'), ('3', 'Praxis extensionistas y construcción colectiva del conocimiento'), ('4', 'Estrategias de gestión integral para el abordaje institucional de la extensión')], max_length=2, null=True, verbose_name='eje'),
        ),
    ]
