# Generated by Django 3.1.2 on 2021-07-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20210724_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_presentation', to='projects.commission', verbose_name='mesa'),
        ),
    ]
