# Generated by Django 3.1.2 on 2021-08-01 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_presentation_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='commission',
        ),
        migrations.AddField(
            model_name='project',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_presentation', to='projects.commission', verbose_name='mesa'),
        ),
    ]
