# Generated by Django 3.1.2 on 2021-08-01 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0033_auto_20210801_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='moderator',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'Collaborator'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderator_commission', to=settings.AUTH_USER_MODEL, verbose_name='moderador'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='technical_operator',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'Collaborator'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technical_operator_commission', to=settings.AUTH_USER_MODEL, verbose_name='operador técnico'),
        ),
    ]
