# Generated by Django 3.1.2 on 2021-08-05 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20210801_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='FECHA Y HORA'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='theme',
            field=models.CharField(blank=True, choices=[('1', 'Políticas públicas y Universidad: el rol de la extensión universitaria en el acompañamiento y asistencia en la pandemia por Covid-19'), ('2', 'Enfoques teóricos, metodológicos y prácticos para la curricularización de la extensión'), ('3', 'Praxis extensionistas y construcción colectiva del conocimiento'), ('4', 'Estrategias de gestión integral para el abordaje institucional de la extensión')], max_length=2, null=True, verbose_name='eje'),
        ),
    ]
