# Generated by Django 3.1.2 on 2021-08-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_audience_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='responsable',
            field=models.CharField(max_length=200, null=True, verbose_name='RESPONSABLE'),
        ),
    ]
