# Generated by Django 3.1.2 on 2021-08-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_workshop_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='moderator',
            field=models.CharField(max_length=200, null=True, verbose_name='moderador'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='technical_operator',
            field=models.CharField(max_length=200, null=True, verbose_name='operador técnico'),
        ),
    ]
