# Generated by Django 3.1.2 on 2021-08-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20210824_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='technical_operator',
            field=models.CharField(max_length=200, null=True, verbose_name='asistente de mesa'),
        ),
    ]
