# Generated by Django 3.1.2 on 2021-09-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20210827_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='technical_operator',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='operador técnico'),
        ),
    ]
