# Generated by Django 3.1.2 on 2020-10-23 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
        ('persons', '0002_auto_20200425_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='university_person', to='universities.university', verbose_name='facultad'),
        ),
        migrations.AlterField(
            model_name='person',
            name='document_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='documento'),
        ),
    ]
