# Generated by Django 3.1.2 on 2020-10-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_auto_20201024_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_type',
            field=models.CharField(choices=[('Subscriber', 'suscriptor'), ('lecturer', 'disertante'), ('collaborator', 'colaborador'), ('organizer', 'organizador')], default='Subscriber', max_length=15, verbose_name='tipo'),
        ),
    ]
