# Generated by Django 3.1.2 on 2020-10-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_person_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_type',
            field=models.CharField(choices=[('Subscriber', 'suscriptor'), ('Lecturer', 'disertante'), ('Collaborator', 'colaborador'), ('Organizer', 'organizador')], default='Subscriber', max_length=15, verbose_name='tipo'),
        ),
    ]
