# Generated by Django 3.1.2 on 2020-10-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_auto_20201025_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_type',
            field=models.CharField(choices=[('Subscriber', 'Suscriptor'), ('Lecturer', 'Disertante'), ('Collaborator', 'Colaborador'), ('Organizer', 'Organizador')], default='Subscriber', max_length=15, verbose_name='tipo'),
        ),
    ]
