# Generated by Django 3.1.2 on 2020-10-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_auto_20201025_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='person',
            name='this_payment',
            field=models.BooleanField(default=False, verbose_name='esta pago'),
        ),
    ]
