# Generated by Django 3.1.2 on 2021-04-16 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_auto_20210415_2152'),
        ('persons', '0010_auto_20210410_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='university_person', to='universities.university', verbose_name='Universidad / Organización'),
        ),
    ]
