# Generated by Django 3.1.2 on 2021-04-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0013_auto_20210417_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='relation',
            field=models.CharField(blank=True, choices=[('Student', 'Estudiante'), ('Teacher', 'Docente'), ('NonTeaching', 'No Docente'), ('Community', 'Comunidad')], default='Student', max_length=15, null=True, verbose_name='tipo'),
        ),
    ]
