# Generated by Django 3.1.2 on 2021-04-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0014_auto_20210417_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='affiliation',
            field=models.CharField(max_length=150, null=True, verbose_name='Filiación'),
        ),
        migrations.AlterField(
            model_name='person',
            name='relation',
            field=models.CharField(blank=True, choices=[('Student', 'Estudiante'), ('Graduate', 'Graduado'), ('Teacher', 'Docente'), ('NonTeaching', 'No Docente'), ('Community', 'Comunidad')], default='Student', max_length=15, null=True, verbose_name='tipo'),
        ),
    ]
