# Generated by Django 3.1.2 on 2021-06-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0017_auto_20210531_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='relation',
            field=models.CharField(blank=True, choices=[('Student', 'Estudiante'), ('Graduate', 'Graduada/o'), ('Teacher', 'Docente'), ('NonTeaching', 'No Docente'), ('Community', 'Comunidad')], default='Student', max_length=15, null=True, verbose_name='relación'),
        ),
    ]
