# Generated by Django 3.1.2 on 2021-06-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0018_auto_20210602_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='document_number',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='documento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
    ]
