# Generated by Django 3.1.2 on 2020-10-23 22:03

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('location', models.CharField(max_length=200, verbose_name='dirección')),
            ],
            options={
                'verbose_name': 'Facultad Regional',
                'verbose_name_plural': 'facultades Regionales',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
