# Generated by Django 3.1.2 on 2020-11-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_auto_20201025_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='dirección'),
        ),
    ]
