# Generated by Django 3.1.2 on 2021-04-16 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_auto_20201104_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Universidad / Organización', 'verbose_name_plural': 'Universidades / Organizaciones'},
        ),
    ]
