# Generated by Django 3.1.2 on 2020-10-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rom',
            new_name='Room',
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='rom',
            new_name='room',
        ),
    ]
