# Generated by Django 3.1.2 on 2020-10-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_auto_20201023_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='link_url',
            field=models.URLField(null=True),
        ),
    ]
