# Generated by Django 3.1.2 on 2020-10-24 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talks', '0003_talk_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='speaker',
        ),
        migrations.AddField(
            model_name='talk',
            name='speakers',
            field=models.ManyToManyField(null=True, related_name='speakers', to=settings.AUTH_USER_MODEL, verbose_name='expositores'),
        ),
    ]
