# Generated by Django 3.1.2 on 2020-10-24 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talks', '0004_auto_20201023_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='speakers',
            field=models.ManyToManyField(related_name='speakers', to=settings.AUTH_USER_MODEL, verbose_name='expositores'),
        ),
    ]
