# Generated by Django 3.1.2 on 2020-10-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0006_talk_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='is_masterful',
            field=models.BooleanField(default=False, verbose_name='es magistral'),
        ),
    ]
