# Generated by Django 3.1.2 on 2020-10-24 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0008_auto_20201024_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='day_talk', to='talks.day', verbose_name='día'),
        ),
    ]
