# Generated by Django 3.1.2 on 2020-10-24 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0009_auto_20201024_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'día', 'verbose_name_plural': 'días'},
        ),
    ]
