# Generated by Django 3.1.2 on 2020-10-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0010_auto_20201024_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(max_length=160, unique=True, verbose_name='titulo'),
        ),
    ]
