# Generated by Django 3.1.2 on 2020-10-27 01:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0011_auto_20201026_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, unique=True, verbose_name='titulo')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='inicio')),
                ('end_time', models.TimeField(default=django.utils.timezone.now, verbose_name='finalización')),
                ('link_url', models.URLField(null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='day_act', to='talks.day', verbose_name='día')),
            ],
            options={
                'verbose_name': 'acto',
                'verbose_name_plural': 'actos',
            },
        ),
    ]
