# Generated by Django 3.1.2 on 2020-10-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0012_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='titulo'),
        ),
    ]
