# Generated by Django 3.1.2 on 2020-11-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0013_auto_20201028_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='active',
            field=models.BooleanField(default=False, verbose_name='día activo'),
        ),
    ]
